In [2]:
import numpy as np

In [3]:
empty_array=np.empty([5,5])
print(empty_array)

[[1.75502868e-316 0.00000000e+000 8.10267659e-322             nan
  2.37923482e+233]
 [3.81888406e+077 1.48773043e+195 7.30298161e-312 2.35967956e-311
  9.57614238e+115]
 [5.37859982e+228 2.17603419e+243 1.98275420e-313 1.43623515e+161
  9.21759543e-314]
 [7.48323561e-206 1.50652414e+161 9.81324182e+242 3.68752608e+059
  7.54792497e+168]
 [3.46417803e-263 4.61704588e-297 8.46929451e-278 1.70601619e+087
  3.84567980e-315]]


In [4]:
zeroes_array=np.zeros([3,4])
print(zeroes_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
ones_array=np.ones([3,1])
print(ones_array)

[[1.]
 [1.]
 [1.]]


In [6]:
id_array=np.identity(3)
id_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])